### ISSUE TITLE
Chart is compressed

### ISSUE THREAD

**Issue by fabianp123** [gpbl/SwiftChart#35] opened 2016-10-13 09:17 UTC
Hey, 

i have a Problem :( i have added the chart to a custom cell and after redrawing the chart is compressed. Do you now the problem? Im using swift 3.

thank you :)

![bildschirmfoto 2016-10-13 um 11 09 49](https://cloud.githubusercontent.com/assets/22002124/19343266/c772a4f4-9135-11e6-8fad-63a0bd8adb8a.png)
![bildschirmfoto 2016-10-13 um 11 10 02](https://cloud.githubusercontent.com/assets/22002124/19343267/c79b2ac8-9135-11e6-9c29-c83b09337cfa.png)

**Comment by gpbl** [comment] 2016-10-13 09:38
👋  @fabianp123!  When do you need to redraw the chart? It seems it isn't getting the right width.
Any chance you can reproduce this issue by cloning this repo?

**Comment by gpbl** [comment] 2017-02-12 16:03
Closing this because lack of info! Please reopen providing with more details. Thanks.

**Closed by gpbl** 2017-02-12 16:03 UTC
